branch-defaults:
  default:
    environment: django-pcp
    group_suffix: null
environment-defaults:
  Pcp-env:
    branch: null
    repository: null
global:
  application_name: pcp
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: python-3.6
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
